consen_iden='0.20'
clust_cov='0.30'
TE_match_iden='0.40'
annot_str_regex='([^.]+\.[^.]+)\..+'
min_align_count="3" # Minimum number of sequences in a family to trigger alignments, modeling, and trees
min_annots_in_align="1" # Minimum number of distinct annotation groups in an alignment to retain it

evalue='1e-10'
search_method='hmmsearch'  # hmmsearch > align_sample
hmmdb_path="/project/legume_project/common_data/genefamilies/legume.fam3.VLMQ" # FULL PATH to hmmpress-d HMMs (minus .h?? suffixes) 

fam_dir='legume.fam3.VLMQ'  # Directory from a previous pandagma-fam run, containing either a hmm_dir or prot_fam_dir
hmm_dir='legume.fam3.VLMQ.baseB_hmm'  # Subdirectory within fam_dir, containing HMMs for realigning sequences in families from this run.

##### (required) list of BED & FASTA file paths
# add file paths to the the annotation_files, cds_files, and protein_files arrays.
# The nth listed BED file corresponds to the nth listed FASTA file.

annotation_files=(
arahy.Tifrunner.gnm2.ann2.PVFB.gene_models_main.bed.gz
cajca.ICPL87119.gnm2.ann1.L3ZH.gene_models_main.bed.gz
cicar.CDCFrontier.gnm3.ann1.NPD7.gene_models_main.bed.gz
glyma.Wm82.gnm4.ann1.T8TQ.gene_models_main.bed.gz
phavu.G19833.gnm2.ann1.PB8d.gene_models_main.bed.gz
vigun.IT97K-499-35.gnm1.ann2.FD7K.gene_models_main.bed.gz
)

cds_files=(
arahy.Tifrunner.gnm2.ann2.PVFB.cds.fna.gz
cajca.ICPL87119.gnm2.ann1.L3ZH.cds_primary.fna.gz
cicar.CDCFrontier.gnm3.ann1.NPD7.cds.fna.gz
glyma.Wm82.gnm4.ann1.T8TQ.cds_primary.fna.gz
phavu.G19833.gnm2.ann1.PB8d.cds_primary.fna.gz
vigun.IT97K-499-35.gnm1.ann2.FD7K.cds_primary.fna.gz
)

protein_files=(
arahy.Tifrunner.gnm2.ann2.PVFB.protein.faa.gz
cajca.ICPL87119.gnm2.ann1.L3ZH.protein_primary.faa.gz
cicar.CDCFrontier.gnm3.ann1.NPD7.protein.faa.gz
glyma.Wm82.gnm4.ann1.T8TQ.protein_primary.faa.gz
phavu.G19833.gnm2.ann1.PB8d.protein_primary.faa.gz
vigun.IT97K-499-35.gnm1.ann2.FD7K.protein_primary.faa.gz
)

### (optional) Fasta file of sequences to use exclude from annotations, e.g. transposable elements or plastid seuqences.
### If provided, sequences in this file will be used to exclude CDS sequences if any matches are >= TE_match_iden
exclude_TE_match_file=(
  legume.TE_lib_2024.rpt.6WVT.fna.gz
)

