clust_iden='0.90'
clust_cov="0.50"
extra_iden='0.80'
TE_match_iden='0.40'
mcl_inflation='1.6'
strict_synt="1"
pctl_low="25"
pctl_med="50"
pctl_hi="75"
consen_prefix='Pisum.pan1'
annot_str_regex='([^.]+\.[^.]+\.[^.]+\.[^.]+)\..+'
preferred_annot='ZW6.gnm1.ann1'
order_method="reference"
min_align_count="4" # Minimum number of sequences in a family to trigger alignments, modeling, and trees
min_annots_in_align="1" # Minimum number of distinct annotation groups in an alignment to retain it

##### (required) list of GFF & FASTA file paths
# Uncomment add file paths to the the annotation_files and cds_files arrays.
# The nth listed GFF file corresponds to the nth listed FASTA file.

annotation_files=(
  pissa.Cameor.gnm2.ann1.KT6X.gene_models_main.bed.gz
  pissa.JI2822.gnm1.ann1.D0QS.gene_models_main.bed.gz
  pissa.ZW6.gnm1.ann1.TKZX.gene_models_main.bed.gz
)

cds_files=(
  pissa.Cameor.gnm2.ann1.KT6X.cds.fna.gz
  pissa.JI2822.gnm1.ann1.D0QS.cds.fna.gz
  pissa.ZW6.gnm1.ann1.TKZX.cds.fna.gz
)

protein_files=(
  pissa.Cameor.gnm2.ann1.KT6X.protein.faa.gz
  pissa.JI2822.gnm1.ann1.D0QS.protein.faa.gz
  pissa.ZW6.gnm1.ann1.TKZX.protein.faa.gz
)

### (optional) Extra GFF & FASTA files
annotation_files_extra_free=(
  pissa.Cameor.gnm1.ann1.7SZR.gene_models_main.bed.gz
)

cds_files_extra_free=(
  pissa.Cameor.gnm1.ann1.7SZR.cds.fna.gz
)

protein_files_extra_free=(
  pissa.Cameor.gnm1.ann1.7SZR.protein.faa.gz
)

### (optional) Fasta file of sequences to use exclude from annotations, e.g. transposable elements or plastid seuqences.
### If provided, sequences in this file will be used to exclude CDS sequences if any matches are >= TE_match_iden
exclude_TE_match_file=(
  legume.TE_lib_2024.rpt.6WVT.fna.gz
)

#### (optional) expected_chr_matches

