FILES ::= \
acacr.Acra3RX.gnm1.ann1.6C0V.cds_primary.fna.gz \
acacr.Acra3RX.gnm1.ann1.6C0V.gene_models_main.bed.gz \
acacr.Acra3RX.gnm1.ann1.6C0V.protein_primary.faa.gz \
aesev.CIAT22838.gnm1.ann1.ZM3R.cds_primary.fna.gz \
aesev.CIAT22838.gnm1.ann1.ZM3R.gene_models_main.bed.gz \
aesev.CIAT22838.gnm1.ann1.ZM3R.protein_primary.faa.gz \
Arachis.pan3.BYQ9.pctl30_named_cds.fna.gz \
Arachis.pan3.BYQ9.pctl30_named_protein.bed.gz \
Arachis.pan3.BYQ9.pctl30_named_protein.faa.gz \
arath.Col0.gnm9.ann11.KH24.cds_primary.fna.gz \
arath.Col0.gnm9.ann11.KH24.gene_models_main.bed.gz \
arath.Col0.gnm9.ann11.KH24.protein_primary.faa.gz \
cerca.ISC453364.gnm3.ann1.3N1M.cds_primary.fna.gz \
cerca.ISC453364.gnm3.ann1.3N1M.gene_models_main.bed.gz \
cerca.ISC453364.gnm3.ann1.3N1M.protein_primary.faa.gz \
chafa.ISC494698.gnm1.ann1.G7XW.cds_primary.fna.gz \
chafa.ISC494698.gnm1.ann1.G7XW.gene_models_main.bed.gz \
chafa.ISC494698.gnm1.ann1.G7XW.protein_primary.faa.gz \
Cicer.pan3.JVTK.pctl25_named_cds.fna.gz \
Cicer.pan3.JVTK.pctl25_named_protein.bed.gz \
Cicer.pan3.JVTK.pctl25_named_protein.faa.gz \
dalod.SKLTGB.gnm1.ann1.R67B.cds.fna.gz \
dalod.SKLTGB.gnm1.ann1.R67B.gene_models_main.bed.gz \
dalod.SKLTGB.gnm1.ann1.R67B.protein.faa.gz \
Glycine.pan5.MKRS.pctl25_named_cds.fna.gz \
Glycine.pan5.MKRS.pctl25_named_protein.bed.gz \
Glycine.pan5.MKRS.pctl25_named_protein.faa.gz \
labpu.Highworth.gnm1.ann1.HJ3B.cds_primary.fna.gz \
labpu.Highworth.gnm1.ann1.HJ3B.gene_models_main.bed.gz \
labpu.Highworth.gnm1.ann1.HJ3B.protein_primary.faa.gz \
lencu.CDC_Redberry.gnm2.ann1.5FB4.cds.fna.gz \
lencu.CDC_Redberry.gnm2.ann1.5FB4.gene_models_main.bed.gz \
lencu.CDC_Redberry.gnm2.ann1.5FB4.protein.faa.gz \
lotja.MG20.gnm3.ann1.WF9B.cds_primary.fna.gz \
lotja.MG20.gnm3.ann1.WF9B.gene_models_main.bed.gz \
lotja.MG20.gnm3.ann1.WF9B.protein_primary.faa.gz \
lupal.Amiga.gnm1.ann1.3GKS.cds.fna.gz \
lupal.Amiga.gnm1.ann1.3GKS.gene_models_main.bed.gz \
lupal.Amiga.gnm1.ann1.3GKS.protein.faa.gz \
Medicago.pan3.9X6B.pctl25_named_cds.fna.gz \
Medicago.pan3.9X6B.pctl25_named_protein.bed.gz \
Medicago.pan3.9X6B.pctl25_named_protein.faa.gz \
Phaseolus.pan3.LXKV.pctl25_named_cds.fna.gz \
Phaseolus.pan3.LXKV.pctl25_named_protein.bed.gz \
Phaseolus.pan3.LXKV.pctl25_named_protein.faa.gz \
pissa.Cameor.gnm1.ann1.7SZR.cds_primary.fna.gz \
pissa.Cameor.gnm1.ann1.7SZR.gene_models_main.bed.gz \
pissa.Cameor.gnm1.ann1.7SZR.protein_primary.faa.gz \
phach.longxuteng.gnm1.ann1.KGX9.cds_primary.fna.gz \
phach.longxuteng.gnm1.ann1.KGX9.gene_models_main.bed.gz \
phach.longxuteng.gnm1.ann1.KGX9.protein_primary.faa.gz \
prupe.Lovell.gnm2.ann1.S2ZZ.cds_primary.fna.gz \
prupe.Lovell.gnm2.ann1.S2ZZ.gene_models_main.bed.gz \
prupe.Lovell.gnm2.ann1.S2ZZ.protein_primary.faa.gz \
quisa.S10.gnm1.ann1.RQ4J.cds_primary.fna.gz \
quisa.S10.gnm1.ann1.RQ4J.gene_models_main.bed.gz \
quisa.S10.gnm1.ann1.RQ4J.protein_primary.faa.gz \
sento.Myeongyun.gnm1.ann1.5WXB.cds.fna.gz \
sento.Myeongyun.gnm1.ann1.5WXB.gene_models_main.bed.gz \
sento.Myeongyun.gnm1.ann1.5WXB.protein.faa.gz \
singl.CAF01.gnm1.ann1.WFKC.cds.fna.gz \
singl.CAF01.gnm1.ann1.WFKC.gene_models_main.bed.gz \
singl.CAF01.gnm1.ann1.WFKC.protein.faa.gz \
tripr.MilvusB.gnm2.ann1.DFgp.cds_primary.fna.gz \
tripr.MilvusB.gnm2.ann1.DFgp.gene_models_main.bed.gz \
tripr.MilvusB.gnm2.ann1.DFgp.protein_primary.faa.gz \
vicfa.Hedin2.gnm1.ann1.PTNK.cds_primary.fna.gz \
vicfa.Hedin2.gnm1.ann1.PTNK.gene_models_main.bed.gz \
vicfa.Hedin2.gnm1.ann1.PTNK.protein_primary.faa.gz \
Vigna.pan3.V294.pctl25_named_cds.fna.gz \
Vigna.pan3.V294.pctl25_named_protein.bed.gz \
Vigna.pan3.V294.pctl25_named_protein.faa.gz \
vitvi.PN40024.gnm2.ann1.V31M.cds_primary.fna.gz \
vitvi.PN40024.gnm2.ann1.V31M.gene_models_main.bed.gz \
vitvi.PN40024.gnm2.ann1.V31M.protein_primary.faa.gz \
legume.TE_lib_2024.rpt.6WVT.fna.gz

include $(dir $(realpath $(lastword $(MAKEFILE_LIST))))/common.mk

